language: python
sudo: required
services:
- docker

env:
  global:
  - MOUNTPOINT: mountpoint
  - OUTPUT_DIR: "ubuntuiso"
  matrix:
  - NAME: ubuntu-14.04.5-server-amd64
    ISO: "${NAME}.iso"
    ISO_URL: "http://releases.ubuntu.com/14.04.5/${ISO}"

install:
- sudo apt-get update
- sudo apt-get install -y wget genisoimage

script:
- wget "${ISO_URL}"
- mkdir -p "${MOUNTPOINT}"
- mkdir -p "${OUTPUT_DIR}"
- sudo mount -o loop "${ISO}" "${MOUNTPOINT}"
- sudo cp -rT "${MOUNTPOINT}" "${OUTPUT_DIR}"
- sudo cp lang "${OUTPUT_DIR}/isolinux/lang"
- sudo cp ks.preseed "${OUTPUT_DIR}"
- sudo cp ks.cfg "${OUTPUT_DIR}"
- sudo cp txt.cfg "${OUTPUT_DIR}/isolinux"
- mkisofs -D -r -V "auto-${NAME}" -cache-inodes -J -l \
    -b "${OUTPUT_DIR}/isolinux/isolinux.bin" \
    -c "${OUTPUT_DIR}/isolinux/boot.cat" \
    -no-emul-boot -boot-load-size 4 -boot-info-table \
    -o "unattended-${NAME}.iso" \
    "${OUTPUT_DIR}"
