language: python
sudo: required
services:
- docker

env:
  global:
  - MOUNTPOINT: mountpoint
  matrix:
  - NAME: ubuntu-14.04.5-server-amd64
    ISO: "${NAME}.iso"
    ISO_URL: "http://releases.ubuntu.com/14.04.5/${ISO}"

install:
- sudo apt-get update
- sudo apt-get install -y wget

script:
- wget "${ISO_URL}"
- mkdir -p "${MOUNTPOINT}"
- sudo mount -o loop "${ISO}" "${MOUNTPOINT}"
